var config = {
    "debug": true,
    "port": 1805,
    "wsEngine": "ws",
    "atachCatalog": "",
    "catalog": "",
    "aport": 2016,
    "pingInterval": 60000,
    "pingTimeout": 20000,
    "filetranfer": true,
    "filemaxsize": 1073741824,
    "filepartsize": 4194304,
    "https": false,
    "rejectUnauthorized": true,
    "key": "",
    "cert": "",
    "ca": "",
    "hostname": "",
    "proccount": 4,
    "autostart": false,
    "blockusers": true,
    "failauftime": 90,
    "failaufcount": 3,
    "blocktime": 300,
    "pgconf": {
        "user": "postgres",
        "host": "192.168.0.10",
        "database": "push0k",
        "password": "YourPassword",
        "port": 5432
    },
    "writelogerrfiles": true,
    "writelogerrtable": true,
    "errlogroom": "9270f68b-3c23-4da6-bfc2-89e079d48ddd",
    "simpleMarkdown": true,
    "codeColour1c": true,
    "contactList": 0,
    "registrationNewUsers": false,
    "registrationRoom": ""
};
module.exports = config;