var config = {
    "debug": true,
    "port": 1901,
    "wsEngine": "",
    "atachCatalog": "",
    "catalog": "",
    "pingInterval": 60000,
    "pingTimeout": 20000,
    "filetranfer": true,
    "filemaxsize": 1073741824,
    "filepartsize": 4194304,
    "https": false,
    "rejectUnauthorized": false,
    "key": "",
    "cert": "",
    "ca": "",
    "hostname": "localhost",
    "proccount": 4,
    "autostart": false,
    "blockusers": true,
    "failauftime": 90,
    "failaufcount": 3,
    "blocktime": 300,
    "writelogerrfiles": true,
    "writelogerrtable": true,
    "errlogroom": "",
    "simpleMarkdown": true,
    "codeColour1c": true,
    "contactList": 0,
    "registrationNewUsers": false,
    "registrationRoom": "",
    "errcatalog": ""
};
module.exports = config;